# Optimus Configuration

[alerts]
    # The format alerts will use, available placeholders are:
    # {color} - The color of the alerts (set below)
    # {player} - The name of the player
    # {check} - The name of the check
    # {dev} - If the check is in development
    # {type} - The check type
    # {total} - The players total VL for that check
    # {ping} - The players ping
    # {tps} - The server tps
    # {version} - The players client version
    format = "&8[{color}!&8] {color}{player} &#D6D6D6failed &#A3A8F0{check} &#D6D6D6{dev}(&#A3A8F0{type}&#D6D6D6) &8&o({total})"
    # Additional placeholders for the hover message:
    # {debug} - Check debug information
    hover-message = [
        "&#D6D6D6Player Ping: &#A3A8F0{ping}",
        "&#D6D6D6Server TPS: &#A3A8F0{tps}",
        "&#D6D6D6Client Version: &#A3A8F0{version}",
        "",
        "&#D6D6D6Check Debug:",
        "&#A3A8F0{debug}"
    ]
    # If alerts should be sent to the console
    console = false

    [alerts.colors]
        # The hex color used for green
        green = "#A3f0AB"
        # The hex color used for green
        yellow = "#EAF0A3"
        # The hex color used for green
        red = "#F0A3A3"
        # The hex color used for green
        dark-red = "#F77777"
        # The amount of VL for {color} to turn yellow
        yellow-vl = 50
        # The amount of VL for {color} to turn red
        red-vl = 100
        # The amount of VL for {color} to turn dark red
        dark-red-vl = 200

[checks]
    [checks.groundspoof]
        [checks.groundspoof.a]
            # If this check is enabled
            enabled = true
            # The amount of VL to give the player each time this check is flagged
            vl = 20
            # If this check will punish
            punishable = false
            # How much VL does the player need to have to run the punishment
            punish-vl = 200
            # The commands to punish a player
            punish-commands = [
                "kick {player} [Optimus] GroundSpoof A"
            ]
    [checks.badpackets]
        [checks.badpackets.a]
            # If this check is enabled
            enabled = true
            # The amount of VL to give the player each time this check is flagged
            vl = 100
            # If this check will punish
            punishable = false
            # How much VL does the player need to have to run the punishment
            punish-vl = 200
            # The commands to punish a player
            punish-commands = [
                "kick {player} [Optimus] BadPackets A"
            ]
        [checks.badpackets.b]
            # If this check is enabled
            enabled = true
            # The amount of VL to give the player each time this check is flagged
            vl = 100
            # If this check will punish
            punishable = false
            # How much VL does the player need to have to run the punishment
            punish-vl = 200
            # The commands to punish a player
            punish-commands = [
                "kick {player} [Optimus] BadPackets B"
            ]
        [checks.badpackets.c]
            # If this check is enabled
            enabled = true
            # The amount of VL to give the player each time this check is flagged
            vl = 100
            # If this check will punish
            punishable = false
            # How much VL does the player need to have to run the punishment
            punish-vl = 200
            # The commands to punish a player
            punish-commands = [
                "kick {player} [Optimus] BadPackets C"
            ]
        [checks.badpackets.d]
            # If this check is enabled
            enabled = true
            # The amount of VL to give the player each time this check is flagged
            vl = 100
            # If this check will punish
            punishable = false
            # How much VL does the player need to have to run the punishment
            punish-vl = 200
            # The commands to punish a player
            punish-commands = [
                "kick {player} [Optimus] BadPackets D"
            ]
        [checks.badpackets.e]
            # If this check is enabled
            enabled = true
            # The amount of VL to give the player each time this check is flagged
            vl = 100
            # If this check will punish
            punishable = false
            # How much VL does the player need to have to run the punishment
            punish-vl = 200
            # The commands to punish a player
            punish-commands = [
                "kick {player} [Optimus] BadPackets E"
            ]

[settings]
    # How long (in ms) to wait before checking the player when the first join
    wait-before-checking = 1000
