main: me.notom3ga.optimus.Optimus
name: Optimus
version: ${version}
api-version: 1.16
author: notOM3GA

permissions:
  optimus.alerts:
    description: Allow the player to recieve alerts.
    default: false
  optimus.bypass:
    description: Allow the player to bypass Optimus.
    default: false
