main: me.notom3ga.optimus.Optimus
name: Optimus
version: ${version}
api-version: 1.16
author: notOM3GA
softdepend:
  - floodgate-bukkit

permissions:
  optimus.alerts:
    description: Allow the player to recieve alerts.
    default: false
  optimus.bypass:
    description: Bypass all checks.
    default: false
  optimus.bypass.groundspoof:
    description: Bypass all GroundSpoof checks.
    default: false
  optimus.bypass.groundspoof.a:
    description: Bypass GroundSpoof A.
    default: false
  optimus.bypass.badpackets:
    description: Bypass all BadPacket checks
    default: false
  optimus.bypass.badpackets.a:
    description: Bypass BadPackets A.
    default: false
  optimus.bypass.badpackets.b:
    description: Bypass BadPackets B.
    default: false
  optimus.bypass.badpackets.c:
    description: Bypass BadPackets C.
    default: false
  optimus.bypass.badpackets.d:
    description: Bypass BadPackets D.
    default: false
  optimus.bypass.badpackets.e:
    description: Bypass BadPackets E.
    default: false
